# PyInstaller spec for JARVIS backend
a = Analysis(
    ['main.py'],
    pathex=[],
    datas=[
        ('.env', '.'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'anyio._backends._asyncio',
        'multipart',
        'aiosqlite',
        'httpx',
        'starlette',
        'pydantic',
        'app',
        'app.routes',
        'app.routes.chat',
        'app.routes.config',
        'app.routes.costs',
        'app.routes.memory',
        'app.routes.plugins',
        'app.routes.privacy',
        'app.routes.tools',
        'app.routes.update',
        'app.routes.voice',
        'app.routes.wakeword',
        'app.routes.scheduler',
        'app.plugins',
        'app.plugins.base',
        'app.plugins.manager',
        'app.plugins.registry',
        'app.model_router',
        'app.vector_memory',
        'app.browser_tools',
        'app.system_tools',
        'chromadb',
        'chromadb.utils',
        'chromadb.utils.embedding_functions',
        'numpy',
        'scipy',
        'scipy.spatial',
        'scipy.spatial.distance',
        'scipy.special',
        'numpy.core',
        'numpy.core.numeric',
        'numpy.ndarray',
    ],
    excludes=['tkinter', 'matplotlib', 'PIL'],
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    name='backend',
    debug=False,
    strip=False,
    upx=True,
    console=True,
)
